name: Project - Existing

on:
  workflow_dispatch:
    inputs:
      controller_url:
        description: 'The URL of AWX/AAP.'
        type: string
      controller_username:
        description:
          'The username to log into the controller. One of username/password or token needs to be provided.'
        type: string
        required: false
      controller_password:
        description:
          'The password to log into the controller. One of username/password or token needs to be provided.'
        type: string
        required: false
      controller_token:
        description:
          'The token to authenticate to the controller. One of username/password or token needs to be provided.'
        type: string
        required: false
      controller_timeout:
        description:
          'The timeout in milliseconds to wait for a call to the controller before erroring out.'
        required: false
        type: number
        default: 5000
      controller_verify_certificate:
        description:
          "Verify if the controller's certificate is valid."
        required: false
        type: boolean
        default: true
      project_id:
        description: "The project ID"
        type: number
      name:
        description: "The project name"
        type: string
      organization:
        description: "The project organization"
        type: string

permissions:
  contents: read

jobs:
  test-awx-project-existing:
    name: Test a existing Project
    runs-on: ubuntu-latest
    steps:
      - name: Create unqiue timestamp
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Start AWX
        id: start-awx
        uses: irunasroot/action-awx-project@releases/v1
        with:
          controller_url: ${{ github.event.inputs.controller_url || vars.CONTROLLER_URL }}
          controller_username: ${{ github.event.inputs.controller_username || secrets.CONTROLLER_USERNAME }}
          controller_password: ${{ github.event.inputs.controller_password || secrets.CONTROLLER_PASSWORD }}
          controller_token: ${{ github.event.inputs.controller_token || secrets.CONTROLLER_TOKEN }}
          controller_timeout: ${{ github.event.inputs.controller_timeout }}
          controller_verify_certificate: ${{ github.event.inputs.controller_verify_certificate }}
          project_id: 6
          name: "Demo Project"
          description: Demo Project - ${{ steps.date.outputs.date }}
          organization: 1
